apiVersion: apps/v1
kind: Deployment

metadata: 
  name: thinknyx
  labels: 
    app: thinknyx

spec: 
  template: 
    metadata: 
      name: myapp
      labels:
        app: thinknyx
    spec: 
      containers: 
        - name: thinknyx-savahnna
          image: kulbhushanmayer/ericsson:bangalore-httpd-1.0
      nodeSelector: 
        app: myapp

  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1 

  replicas: 1
  selector: 
    matchLabels: 
      app: thinknyx
