apiVersion: apps/v1
kind: Deployment

metadata: 
  name: thinknyx
  labels: 
    app: thinknyx

spec: 
  template: 
    metadata: 
      name: myapp
      labels:
        app: thinknyx
    spec: 
      containers: 
        - name: thinknyx-savahnna
          image: kulbhushanmayer/ericsson:bangalore-httpd-1.0
          volumeMounts:
            - name: htdocs
              mountPath: /usr/local/apache2/htdocs
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: htdocs
          hostPath:
            path: /var/application
            type: Directory
      nodeSelector: 
        app: myapp
      tolerations:
        - key: "team"
          operator: "Equal"
          value: "thinknyx"
          effect: "NoSchedule"

  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1 

  replicas: 1
  selector: 
    matchLabels: 
      app: thinknyx


---

apiVersion: v1
kind: Service
metadata:
  name: thinknyx
spec:
  type: NodePort
  selector:
    app: thinknyx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32123 

