apiVersion: v1
kind: Pod

metadata: 
  name: myapp
  labels: 
    app: myapp

spec: 
  containers: 
    - name: thinkyx-savahnna
      image: kulbhushanmayer/ericsson:bangalore-httpd-1.0
  nodeSelector: 
    app: myapp
